_welcome_dacore:
  path: /welcome_dacore
  defaults: { _controller: DacorpCoreBundle:Default:index }

change_lang:
    path:   /changelang/{newlang}
    defaults:  { _controller: DacorpCoreBundle:Default:switchLanguage }
    requirements:
        newlang: en|fr|de
#    options: { i18n: false }


dacorp_core_thirdparty:
    resource: "@DacorpCoreBundle/Resources/config/routing_thirdparty.yml"

dacorp_core_ajax:
    resource: "@DacorpCoreBundle/Resources/config/routing_ajax.yml"
    prefix: /ajax